### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by lumodon** [Nogg-aholic/ContentLib_Recipes#1]
Documentation in README.md as well as within Satisfactory Mod Manager make a reference to something called "ContentInspector"
Google searching the following returned no useful results related to Satisfactory nor modding in general:
* `ContentInspector`
* `"satisfactory" game "ContentInspector"`
* `"satisfactory" "ContentInspector"`
* `"ContentInspector" mod`

Please include a hyperlink in README.md and/or Mod page to reference this "ContentInspector" mentioned in your two mods, `ContentLib Recipes` & `ContentLib Items`

----

In case it matters, to avoid [X Y Problem](https://xyproblem.info/) I've been searching _extensively_ to figure out where I can find a list of those "Internal Names" mentioned **_without needing to_ install UE4ed, Visual Studio, Unreal `.pak` unpacker or other** and was hoping whatever this `ContentInspector` is supposed to reference could be viable for obtaining a text-list of all in-game item monikers mapped to their plain English names / in-game descriptions.

**Comment by budak7273** [comment]
Thanks for being so thorough with your search before posting here. 

ContentInspector is a mod that Nog wrote that allows live inspecting (and in some cases, editing) of objects in the game, as well as mod/gmae package structures. It has very little documentation, and a kinda steep learning curve, as it is not really finished yet. But it works in its current form. If you have any questions on how to use it, please stop by the Nog's Mods discord, linked on the mod page.

When I wrote up the mod pages for ContentLib Recipes and Items, I was expecting it to be released a few days later, but it ended up slightly delayed, so I didn't have the links at the time.

I have since updated the mod pages with links to ContentInspector, which you can find here as well: https://ficsit.app/mod/F3gKrk7S5nbSBN

**Comment by lumodon** [comment]
Thank you

Resolved on mod page and in this comment: https://github.com/Nogg-aholic/ContentLib_Recipes/issues/1#issuecomment-906017286

Resolution: This link here: https://ficsit.app/mod/F3gKrk7S5nbSBN
